config:
   oidc_verify_cert: true
   email_identity: string
   ldap_group_search_filter: string
   auth_mode: database 
   self_registration: true
   oidc_scope: string
   ldap_search_dn: string
   storage_per_project: string
   scan_all_policy: 
   type: string
   parameter: 
     daily_time: 0
   verify_remote_cert: true
   ldap_timeout: 0
   ldap_base_dn: string
   ldap_filter: string
   read_only: true
   quota_per_project_enable: true
   ldap_url: string
   oidc_name: string
   project_creation_restriction: string
   ldap_uid: string
   oidc_client_id: string
   ldap_group_base_dn: string
   ldap_group_attribute_name: string
   email_insecure: true
   ldap_group_admin_dn: string
   email_username: string
   oidc_endpoint: string
   oidc_client_secret: string
   ldap_scope: 0
   count_per_project: string
   token_expiration: 0
   ldap_group_search_scope: 0
   email_ssl: true
   email_port: 0
   email_host: string
   email_from: string
